### ISSUE TITLE
Implement date generalisation rules in service

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/sds-webapp2#12]
Currently Sensitive data generalisations are performed in two places: SDS itself and biocache-store. 

To allow for a cleaner decoupling between sensitive data concerns and data interpretation/ingestion it is important that current date generalisation logic performed in biocache-store is extracted to SDS.

This is a dependency for LA pipelines implementation.

**Comment by adam-collins** [comment]
biocache-store is no longer in use, so this happens only in one place now.
