### ISSUE TITLE
Biocache store sensitive data processing analysis and refactoring

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/sds-webapp2#13]
Currently Sensitive data generalisations are performed in two places: SDS itself and biocache-store.

biocache-store code needs to be analysed to identify any logic around sensitive data generalisation and if existing that logic needs to be refactored to reside in SDS.

This is a dependency for LA pipelines implementation.

**Comment by adam-collins** [comment]
biocache-store is not in use. This only happens in one place now.
