### ISSUE TITLE
SDS Outages

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/sds-webapp2#24]
https://confluence.csiro.au/display/ALASD/Outages+and+Incidents

June 2nd 11:48pm - June 3rd 6:16pm | SDS | Starting at 11:48pm on June 2nd our uptime alerting reported SDS to be down. At around 6:10pm on June 3rd a member of the systems attempted to connect to the instance via ssh to investigate however it was unreachable. The instance was restarted from the AWS console and service was restored at 6:16pm | As with the June 1st SDS outage there was a status check failure on the instance ( instance unreachable ) but this was after the initial outage, it's uncertain if this was the cause or due to the outage itself.More investigation needed to determine the root cause.

June 1st 3:22am - 3:42am. 4:18am - 8:03am | SDS | Starting at 3:22am on June 1st our uptime alerting reported SDS to be down. It came back without intervention at 3:42am then was offline again at 4:18am. At around 7:45am a member of the systems team attempted to ssh to the server but it was not responding. Zabbix graphs showed a period of high CPU from around 3:00am to 3:50am. After that time there is no data. Instance graphs in AWS showed a period of high CPU and network traffic dropping off during the event. A status check had been failing since 5:35am. At around 7:50am a server reboot was attempted from the AWS console. By 7:55am the server was reachable by ssh and had started reporting in Zabbix again but the SDS service remained down. At 8:03am the SDS service became available again.Instance CPU from AWS. Times in UTCNetwork in from AWS. Times in UTCZabbix CPU graphThe SDS logs had a large number of stack traces with the repeated message 2023-06-01 03:46:29.297  WARN --- [0.1-8080-exec-5] g.a.s.a.o.a.admin.SystemMessageService   : Could not getSystemMessageFileBut this was appearing before and after the outage alsoLogs provided here for further analysis sds.log.gz | 2023-06-01 03:46:29.297  WARN --- [0.1-8080-exec-5] g.a.s.a.o.a.admin.SystemMessageService   : Could not getSystemMessageFile | There was a status check failure on the instance ( instance unreachable ) but this was after the initial outage, it's uncertain if this was the cause or due to the outage itself. More investigation needed to determine the root cause.

2023-06-01 03:46:29.297  WARN --- [0.1-8080-exec-5] g.a.s.a.o.a.admin.SystemMessageService   : Could not getSystemMessageFile

June 1st 3:22am - 3:42am. 
4:18am - 8:03am
SDS	
Starting at 3:22am on June 1st our uptime alerting reported SDS to be down. It came back without intervention at 3:42am then was offline again at 4:18am. At around 7:45am a member of the systems team attempted to ssh to the server but it was not responding. Zabbix graphs showed a period of high CPU from around 3:00am to 3:50am. After that time there is no data. Instance graphs in AWS showed a period of high CPU and network traffic dropping off during the event. A status check had been failing since 5:35am. At around 7:50am a server reboot was attempted from the AWS console. By 7:55am the server was reachable by ssh and had started reporting in Zabbix again but the SDS service remained down. At 8:03am the SDS service became available again.
Instance CPU from AWS. Times in UTC

Network in from AWS. Times in UTC

Zabbix CPU graph

The SDS logs had a large number of stack traces with the repeated message 
2023-06-01 03:46:29.297  WARN --- [0.1-8080-exec-5]
 g.a.s.a.o.a.admin.SystemMessageService   : Could not getSystemMessageFile
But this was appearing before and after the outage also
Logs provided here for further analysis [sds.log.gz](https://confluence.csiro.au/download/attachments/1298728696/sds.log.gz?version=1&modificationDate=1685572157173&api=v2)
There was a status check failure on the instance ( instance unreachable ) but this was after the initial outage, it's uncertain if this was the cause or due to the outage itself. More investigation needed to determine the root cause.

**Comment by adam-collins** [comment]
The `getSystemMessageFile` exception is fixed. It is a fault in the ala-install. `getSystemMessageFile` requires `/data/sds-webapp2/config/` not `/data/sds/config/`.

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/ala-install/commit/2a72deb7e323033e80064801074b2e498d93f345

**Comment by sughics** [comment]
Moving this to correct repo https://github.com/AtlasOfLivingAustralia/sds-webapp2
